"""Added path_prefix and filename to Certificate table

Revision ID: c7a7784f54c1
Revises: dafa06748d4e
Create Date: 2021-08-11 18:47:50.070081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a7784f54c1'
down_revision = 'dafa06748d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('path_prefix', sa.String(), nullable=True))
    op.add_column('certificates', sa.Column('filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'filename')
    op.drop_column('certificates', 'path_prefix')
    # ### end Alembic commands ###
