"""Initial Migration

Revision ID: dafa06748d4e
Revises: 
Create Date: 2021-06-01 21:56:26.173588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafa06748d4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('death', 'birth', 'marriage_license', 'marriage', name='certificate_type'), nullable=False),
    sa.Column('county', sa.Enum('richmond', 'queens', 'manhattan', 'kings', 'bronx', name='county'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificates')
    # ### end Alembic commands ###
