"""Initial Migration

Revision ID: e09fefb2cf76
Revises: 
Create Date: 2021-09-13 20:29:50.966594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09fefb2cf76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('death', 'birth', 'marriage_license', 'marriage', name='certificate_type'), nullable=False),
    sa.Column('county', sa.Enum('queens', 'manhattan', 'kings', 'bronx', 'richmond', name='county'), nullable=False),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('age', sa.String(length=10), nullable=True),
    sa.Column('soundex', sa.String(length=4), nullable=True),
    sa.Column('path_prefix', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificates')
    # ### end Alembic commands ###
